### ISSUE TITLE
permissions not correct

### ISSUE THREAD

**Issue by getriebesand** [jawainc/simplecontact#17]
In controllers/SimpleContact.php 
`public $requiredPermissions = ['zainab.simplecontact.messages'];`
should be
`public $requiredPermissions = ['zainab.simplecontact.inbox'];`

and in plugin.yaml the permissions should be:

```
permissions:
    zainab.simplecontact.inbox:
        tab: 'zainab.simplecontact::lang.simplecontact.permission'
        label: 'zainab.simplecontact::lang.simplecontact.permission_messages'
    zainab.simplecontact.manage_settings:
        tab: 'zainab.simplecontact::lang.simplecontact.permission'
        label: 'zainab.simplecontact::lang.simplecontact.permission_settings'
```
